<?php

namespace ShipStream\Ups\Api\Model;

class PickupCreationResponse extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property) : bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Response Container.
     *
     * @var PickupCreationResponseResponse
     */
    protected $response;
    /**
     * Pickup Request Number generated by UPS pickup system when a successful pickup is scheduled.Same PRN will be returned if a pickup request already exists for a pickup address/ point.
     *
     * @var string
     */
    protected $pRN;
    /**
     * WeekendServiceTerritory Container.Returned if the  subversion greater or equal to 2007.
     *
     * @var PickupCreationResponseWeekendServiceTerritory
     */
    protected $weekendServiceTerritory;
    /**
    * Indicates if the pickup address qualifies for WST (Weekend Service Territory). Returned if the pickup date is Saturday and subversion greater or equal to 1607. Valid Values:
    - Y = WST
    - N = Non-WST
    *
    * @var string
    */
    protected $weekendServiceTerritoryIndicator;
    /**
     * The rating result of on-callpickup
     *
     * @var PickupCreationResponseRateStatus
     */
    protected $rateStatus;
    /**
     * The result of rating on-callpickup. It correlates to rate status code 01
     *
     * @var PickupCreationResponseRateResult
     */
    protected $rateResult;
    /**
     * Response Container.
     *
     * @return PickupCreationResponseResponse
     */
    public function getResponse() : PickupCreationResponseResponse
    {
        return $this->response;
    }
    /**
     * Response Container.
     *
     * @param PickupCreationResponseResponse $response
     *
     * @return self
     */
    public function setResponse(PickupCreationResponseResponse $response) : self
    {
        $this->initialized['response'] = true;
        $this->response = $response;
        return $this;
    }
    /**
     * Pickup Request Number generated by UPS pickup system when a successful pickup is scheduled.Same PRN will be returned if a pickup request already exists for a pickup address/ point.
     *
     * @return string
     */
    public function getPRN() : string
    {
        return $this->pRN;
    }
    /**
     * Pickup Request Number generated by UPS pickup system when a successful pickup is scheduled.Same PRN will be returned if a pickup request already exists for a pickup address/ point.
     *
     * @param string $pRN
     *
     * @return self
     */
    public function setPRN(string $pRN) : self
    {
        $this->initialized['pRN'] = true;
        $this->pRN = $pRN;
        return $this;
    }
    /**
     * WeekendServiceTerritory Container.Returned if the  subversion greater or equal to 2007.
     *
     * @return PickupCreationResponseWeekendServiceTerritory
     */
    public function getWeekendServiceTerritory() : PickupCreationResponseWeekendServiceTerritory
    {
        return $this->weekendServiceTerritory;
    }
    /**
     * WeekendServiceTerritory Container.Returned if the  subversion greater or equal to 2007.
     *
     * @param PickupCreationResponseWeekendServiceTerritory $weekendServiceTerritory
     *
     * @return self
     */
    public function setWeekendServiceTerritory(PickupCreationResponseWeekendServiceTerritory $weekendServiceTerritory) : self
    {
        $this->initialized['weekendServiceTerritory'] = true;
        $this->weekendServiceTerritory = $weekendServiceTerritory;
        return $this;
    }
    /**
    * Indicates if the pickup address qualifies for WST (Weekend Service Territory). Returned if the pickup date is Saturday and subversion greater or equal to 1607. Valid Values:
    - Y = WST
    - N = Non-WST
    *
    * @return string
    */
    public function getWeekendServiceTerritoryIndicator() : string
    {
        return $this->weekendServiceTerritoryIndicator;
    }
    /**
    * Indicates if the pickup address qualifies for WST (Weekend Service Territory). Returned if the pickup date is Saturday and subversion greater or equal to 1607. Valid Values:
    - Y = WST
    - N = Non-WST
    *
    * @param string $weekendServiceTerritoryIndicator
    *
    * @return self
    */
    public function setWeekendServiceTerritoryIndicator(string $weekendServiceTerritoryIndicator) : self
    {
        $this->initialized['weekendServiceTerritoryIndicator'] = true;
        $this->weekendServiceTerritoryIndicator = $weekendServiceTerritoryIndicator;
        return $this;
    }
    /**
     * The rating result of on-callpickup
     *
     * @return PickupCreationResponseRateStatus
     */
    public function getRateStatus() : PickupCreationResponseRateStatus
    {
        return $this->rateStatus;
    }
    /**
     * The rating result of on-callpickup
     *
     * @param PickupCreationResponseRateStatus $rateStatus
     *
     * @return self
     */
    public function setRateStatus(PickupCreationResponseRateStatus $rateStatus) : self
    {
        $this->initialized['rateStatus'] = true;
        $this->rateStatus = $rateStatus;
        return $this;
    }
    /**
     * The result of rating on-callpickup. It correlates to rate status code 01
     *
     * @return PickupCreationResponseRateResult
     */
    public function getRateResult() : PickupCreationResponseRateResult
    {
        return $this->rateResult;
    }
    /**
     * The result of rating on-callpickup. It correlates to rate status code 01
     *
     * @param PickupCreationResponseRateResult $rateResult
     *
     * @return self
     */
    public function setRateResult(PickupCreationResponseRateResult $rateResult) : self
    {
        $this->initialized['rateResult'] = true;
        $this->rateResult = $rateResult;
        return $this;
    }
}