<?php

namespace ShipStream\Ups\Api\Model;

class PickupCancelRequest extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property) : bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Request Container.
     *
     * @var PickupCancelRequestRequest
     */
    protected $request;
    /**
    * Cancel pickup by Pickup Request Number (PRN).
    - 01= Account Number
    - 02 = PRN
    *
    * @var string
    */
    protected $cancelBy;
    /**
    * The pickup request number (PRN) generated by UPS pickup system.
    Required if CancelBy = 02
    *
    * @var string
    */
    protected $pRN;
    /**
     * Request Container.
     *
     * @return PickupCancelRequestRequest
     */
    public function getRequest() : PickupCancelRequestRequest
    {
        return $this->request;
    }
    /**
     * Request Container.
     *
     * @param PickupCancelRequestRequest $request
     *
     * @return self
     */
    public function setRequest(PickupCancelRequestRequest $request) : self
    {
        $this->initialized['request'] = true;
        $this->request = $request;
        return $this;
    }
    /**
    * Cancel pickup by Pickup Request Number (PRN).
    - 01= Account Number
    - 02 = PRN
    *
    * @return string
    */
    public function getCancelBy() : string
    {
        return $this->cancelBy;
    }
    /**
    * Cancel pickup by Pickup Request Number (PRN).
    - 01= Account Number
    - 02 = PRN
    *
    * @param string $cancelBy
    *
    * @return self
    */
    public function setCancelBy(string $cancelBy) : self
    {
        $this->initialized['cancelBy'] = true;
        $this->cancelBy = $cancelBy;
        return $this;
    }
    /**
    * The pickup request number (PRN) generated by UPS pickup system.
    Required if CancelBy = 02
    *
    * @return string
    */
    public function getPRN() : string
    {
        return $this->pRN;
    }
    /**
    * The pickup request number (PRN) generated by UPS pickup system.
    Required if CancelBy = 02
    *
    * @param string $pRN
    *
    * @return self
    */
    public function setPRN(string $pRN) : self
    {
        $this->initialized['pRN'] = true;
        $this->pRN = $pRN;
        return $this;
    }
}